# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_newsinfo_newstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(max_length=20)),
                ('areaParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.AreaInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsInfo',
        ),
        migrations.DeleteModel(
            name='NewsType',
        ),
    ]
